config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  put 'books/:id' => 'books#update'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      #show画面へのリダイレクト
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>

  <h1>Editing Book</h1>

  <% if @book.errors.any? %>
  <div class="error-explanation">
      <h2 class="field_with_errors"><%= @book.errors.count %> error prohibited this book from being saved:</h2>
      <ul class="field_with_errors"><% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  </div>
  <% end %>

  <%= form_with model:@book, local: true do |f| %>
      <div class="field">
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <h4>Body</h4>
        <%= f.text_area :body %>
      </div>
      <div class="actions">
        <%= f.submit 'Update Book' %>
      </div>
  <% end %>

    <%= link_to "Show", book_path(@book.id) %>
  |
    <%= link_to "Back", "/books" %>
</body>

app/views/books/index.html.erb
<body>
  <% if flash[:notice] %>
      <p id="notice">
          <%= flash[:notice] %>
      </p>
  <% end %>

  <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book_path(book) %></td>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
          <td><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>


    <h2 class="new-book">New book</h2>
    <% if @book.errors.any? %>
      <div class="error-explanation">
        <h2 class="error-message"><%= @book.errors.count %> error prohibited this book from being saved:</h2>
        <ul class=error-content><% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <%= form_with model: @book, url:'/books', local:true do |f| %>
      <div class="field">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <label for="book_body">Body</label>
        <%= f.text_area :body %>
      </div>


      <div class="actions">
        <%= f.submit 'Create Book' %>
      </div>

    <% end %>
</body>

app/views/books/show.html.erb
<body>
    <% if flash[:notice] %>
      <p id="notice">
          <%= flash[:notice] %>
      </p>
    <% end %>

    <p class="title"><strong>Title: </strong><%= @book.title %></p>

    <p class="body"><strong>Body: </strong><%= @book.body %></p>



      <%= link_to "Edit", edit_book_path(@book.id) %>
    |
      <%= link_to "Back", "/books" %>

</body>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong>へ！</h1>
  <p class="top-sentence"><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
  <p class="top-sentence">印象を共有し交換することができます</p>
  <p class="top-sentence">
    <%= link_to "start", "/books" %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Initialbookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>